# Spring properties
spring:
  application:
     name: post-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 1113   # HTTP (Tomcat) port